import {
    ArrowDownIcon,
    ArrowUpIcon,
    BookIcon,
    Bookmark,
    BugIcon,
    CalendarFoldIcon,
    CalendarIcon,
    CheckIcon,
    ChevronDownIcon,
    ChevronLeftIcon,
    ChevronRightIcon,
    ChevronsLeftIcon,
    ChevronsRightIcon,
    ChevronsUpDownIcon,
    CircleXIcon,
    ClockIcon,
    Command,
    DatabaseIcon,
    DownloadIcon,
    EraserIcon,
    FileIcon,
    FileTextIcon,
    FilterIcon,
    FolderIcon,
    GlobeIcon,
    GraduationCapIcon,
    HeadsetIcon,
    HelpCircleIcon,
    HomeIcon,
    InfoIcon,
    LeafIcon,
    LightbulbIcon,
    LineChartIcon,
    Link2Icon,
    Link2OffIcon,
    LinkIcon,
    Loader2Icon,
    LogOutIcon,
    MapPinIcon,
    Moon,
    Package2Icon,
    PackageIcon,
    PanelLeftCloseIcon,
    PanelLeftIcon,
    PanelLeftOpenIcon,
    PanelTopIcon,
    PencilIcon,
    PlusCircleIcon,
    PlusIcon,
    RadioIcon,
    SaveIcon,
    SchoolIcon,
    SearchIcon,
    SettingsIcon,
    ShoppingCartIcon,
    SunMedium,
    Trash2Icon,
    TriangleAlertIcon,
    UploadIcon,
    UserIcon,
    Users2Icon,
    XIcon,
    ZapIcon,
} from "lucide-react";
import type { LucideProps } from "lucide-react";
import { cn } from "@/lib/utils";

interface IconProps extends LucideProps {
    name: keyof typeof Icons;
}

export const Icons = {
    home: HomeIcon,
    lineChart: LineChartIcon,
    package2: Package2Icon,
    package: PackageIcon,
    settings: SettingsIcon,
    shoppingCart: ShoppingCartIcon,
    user: UserIcon,
    users: Users2Icon,
    search: SearchIcon,
    sidebar: PanelLeftIcon,
    logo: Command,
    sun: SunMedium,
    moon: Moon,
    thunder: ZapIcon,
    lightbulb: LightbulbIcon,
    leaf: LeafIcon,
    invoice: FileTextIcon,
    live: RadioIcon,
    support: HeadsetIcon,
    leftArrow: ChevronLeftIcon,
    rightArrow: ChevronRightIcon,
    logout: LogOutIcon,
    bug: BugIcon,
    link: Link2Icon,
    book: BookIcon,
    bookmark: Bookmark,
    dashboard: PanelTopIcon,
    date: CalendarIcon,
    school: SchoolIcon,
    form: FolderIcon,
    pencil: PencilIcon,
    trash: Trash2Icon,
    plus: PlusIcon,
    save: SaveIcon,
    draft: EraserIcon,
    db: DatabaseIcon,
    unlink: Link2OffIcon,
    "chevron-down": ChevronDownIcon,
    check: CheckIcon,
    world: GlobeIcon,
    cancel: XIcon,
    calendar: CalendarFoldIcon,
    chevronsUpDown: ChevronsUpDownIcon,
    error: CircleXIcon,
    download: DownloadIcon,
    warning: TriangleAlertIcon,
    plusCircle: PlusCircleIcon,
    graduationCap: GraduationCapIcon,
    "arrow-left": ChevronLeftIcon,
    "arrow-right": ChevronRightIcon,
    questionMark: HelpCircleIcon,
    remove: XIcon,
    upload: UploadIcon,
    report: FileTextIcon,
    spinner: Loader2Icon,
    file: FileIcon,
    clock: ClockIcon,
    arrowDown: ArrowDownIcon,
    arrowUp: ArrowUpIcon,
    sort: ChevronsUpDownIcon,
    filter: FilterIcon,
    doubleArrowLeft: ChevronsLeftIcon,
    doubleArrowRight: ChevronsRightIcon,
    arrowLeft: ChevronLeftIcon,
    arrowRight: ChevronRightIcon,
    chevronDown: ChevronDownIcon,
    panelLeftClose: PanelLeftCloseIcon,
    panelLeftOpen: PanelLeftOpenIcon,
    info: InfoIcon,
    location: MapPinIcon,
};

export function Icon({
    name,
    className,
    ...props
}: IconProps): React.ReactElement | null {
    const LucideIcon = Icons[name];

    if (!LucideIcon) {
        return null;
    }

    return <LucideIcon className={cn("shrink-0", className)} {...props} />;
}

export type IconNames = keyof typeof Icons;
export const IconNames = Object.keys(Icons) as IconNames[];
